version: '3'

services:

       web:
              image: nginx:latest
              ports:
                     - "8088:80"
                     # - "9086:443"
                     # - '${VITE_PORT:-3000}:${VITE_PORT:-3000}'
              volumes:
                     - ./src:/var/www/html
                     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
              links:
                     - app
                     # - postgres
                     # - redis

       app:
              image: meuphp82
              volumes:
                     - ./src:/var/www/html
                     - ./app/limits.ini:/usr/local/etc/php/conf.d/limits.ini
              env_file:
                     - ./env/app.env
              ports:
                     - '${VITE_PORT:-5174}:${VITE_PORT:-5174}'
  
networks:
       postgres:
              driver: bridge
volumes:
       postgres:
       cache: